addons:
  apt:
    packages:
    - libgmp-dev
after_success:
- |
  if test "$TRAVIS_TAG" -a "$TRAVIS_OS_NAME" = linux
  then
    mkdir -p "$HOME/.stack/upload"
    echo "{ \"username\": \"$HACKAGE_USERNAME\", \"password\": \"$HACKAGE_PASSWORD\" }" > "$HOME/.stack/upload/credentials.json"
    stack upload --no-signature .
  fi
- |
  if test "$TRAVIS_TAG" -a "$GITHUB_TOKEN"
  then
    gzip --best --to-stdout "$(stack path --local-install-root)/bin/sensu-run" > sensu-run.gz
    stack exec -- sensu-run upload \
      --token "$GITHUB_TOKEN" \
      --owner tfausak \
      --repo sensu-run \
      --tag "$TRAVIS_TAG" \
      --file sensu-run.gz \
      --name "sensu-run-$TRAVIS_TAG-$TRAVIS_OS_NAME.gz"
  fi
before_install:
- |
  if test ! -f "$HOME/.local/bin/stack"
  then
    URL="https://www.stackage.org/stack/$TRAVIS_OS_NAME-x86_64"
    curl --location "$URL" > stack.tar.gz
    gunzip stack.tar.gz
    tar -x -f stack.tar --strip-components 1
    mkdir -p "$HOME/.local/bin"
    mv stack "$HOME/.local/bin/"
  fi
cache:
  directories:
  - "$HOME/.local/bin"
  - "$HOME/.stack"
env:
  global:
  - HACKAGE_USERNAME=MitsutoshiAoe
  - secure: Lv2XqQhaXoWCFrbv+L8Zr4uqDXky2B1qL3MFzG4SqI8qZ3d+OOHtY61/P/x/CUtjtHETKaWNKwKAtXJosc/mv7DK+XUcJr/FVuX/thD94B+2vqy3gEWR9SQxZjocwG5TtpphlZD4hKFt68Ulz2cNyXJ0ddnUmJgVOgv7MIIVLGik7CRpSL1THlF7r7gh3/Ipsa8giG9cYyI1Ha3TYj1dOrmMy1nVbOleDgyawiR4YDHRgSXC/4832OLlObO3GF0VopqW0Q6KkG59ascE37+7yBCGsISlGsp4imUFF1VE08KBBalv3X0IymiTHzurobJJbJEBT2+qBR7LfcWy6dpYaUBJhj1kCn/CYkqjaH5Ha8y9bG7gO7xPxM205xaaxhGj0rr/WLbVoFXEz0X7QGYDchyGkAVN/NJfdX7q85qZqgobI9rO0Myr1JZAk7vsCWx4m8QN384owZkanUcdP6efKdsjSdR8V3mfoSNhSPAi0mNhYDtxRzopXYY+O+1PFcbZJmn7XwteNfwxKP0hu0XjKoE0+lfz40WalXGLrFHXrON73tON3AZ1NPYpyxsXOaxperLJC7piECWqLp5b6f7xC7CryjcMwBzv+NEdHRSYdUlmfZTVH7G8VCCGncKkE+RGOjf/t1ETW/hVBnQ7MYInaWTz7MWhBuLVjABT3j8mtJU=
  - secure: lbJhnaVHbt4iSGjOXlWU6Wg7TBMT3FidLSbWb9PQAy3hWrtaAySYk1YijSo5QTEigFZvmrkJ7akx2upKS7KwyCybfIF+HSDJ+QEkov/xs1ZxWt6+ZCK1wj9razAe08RaxI5J3nac/18d68akAPwqnZgM2TbifgPPuziDg1ghLmTmXOaiEJa75+md6q6DiEG/H26cJrbyGSXPDLCwyO78b6ymU+mJgILn6LUO5hp2jLC0aPaoA3/SJ7EBtDmVjYKjSCoeivl2E5hpS0TWd8+yMpkGpxnYLxqsy8AP1pTToQOWdPVhp2LtMiknYUjzHIt0LgndXrRYfEKIgrZvxztYFU8Rxj0UWeJkuXknbppgiM4OJH9iHBDbtoUn8tvGwBvcqVgtimY+FCqsv3TgebJGt6oYm5bl+x4AAWkksv3wCx6EUJRWeOfiuT4udp4kRAZzJt8hIDTtWtv3sdxpxCa7VCSKruPkmDrXNPcDajPsH/HRi5IOvyR7atY7+YFKjN2++LdE+q8rT25UyZuHUekQKe9fsIsBL/9ToZzsiVIt/kNSBzJ4kQm7kqQkn7t4pp7R1N8hMrB1h3O0fHC5ATgY4OUuuqWd4FBFNiVDda4X1mNBvEjdnX51qv0NM4aCBXhi3P3voox7KZil1uz9qwN+sqWgrl0B7xAg35FQc+ScfPo=
language: c
os:
- linux
- osx
script:
- stack setup
- stack --no-terminal build --pedantic
- stack sdist
sudo: false
