addons:
  apt:
    packages:
    - libgmp-dev
before_install:
- |
  if test ! -f "$HOME/.local/bin/stack"
  then
    URL="https://www.stackage.org/stack/$TRAVIS_OS_NAME-x86_64"
    curl --location "$URL" > stack.tar.gz
    gunzip stack.tar.gz
    tar -x -f stack.tar --strip-components 1
    mkdir -p "$HOME/.local/bin"
    mv stack "$HOME/.local/bin/"
  fi
cache:
  directories:
  - "$HOME/.local/bin"
  - "$HOME/.stack"
language: c
os:
- linux
- osx
script:
- stack setup
- stack --no-terminal build --pedantic
- stack sdist
sudo: false
