shallow_clone: true
environment:
  global:
    STACK_ROOT: c:\s
  matrix:
  - PLATFORM: x64
    MSYS: msys64
    STACK_ARCH: x86_64
  - PLATFORM: x86
    MSYS: msys32
    STACK_ARCH: i386
cache:
- c:\s -> appveyor.yml
version: '{build}'
install:
- curl -ostack.zip -LsS --insecure https://www.stackage.org/stack/windows-%STACK_ARCH%
- 7z x stack.zip stack.exe
- stack.exe setup > nul
- stack.exe --no-terminal build -j1 --only-dependencies
build_script:
- stack.exe --no-terminal build -j1 --pedantic
test_script:
- stack.exe exec sensu-run
- stack.exe exec sensu-run -- --name check-test --handler test --dry-run -- echo test
- stack.exe sdist
after_test:
- ps: cp "$(./stack.exe path --local-install-root)/bin/sensu-run.exe" sensu-run.exe
- 7z a sensu-run.windows.%PLATFORM%.zip sensu-run.exe
artifacts:
- path: sensu-run.windows.%PLATFORM%.zip
deploy:
- provider: GitHub
  auth_token:
    secure: VfuGAeBDY+lUA7omIc8uMUNjvHwx34amMq34spLVP1nC0fR/ift6IGQCDguWipxF
  artifact: sensu-run.windows.$(platform).zip
  release: $(appveyor_repo_tag_name)
  draft: true
  on:
    appveyor_repo_tag: true
