platform: x64
cache:
- c:\s -> appveyor.yml
environment:
  STACK_ROOT: c:\s
version: '{build}'
install:
- ps: curl -OutFile stack.zip -Uri https://github.com/commercialhaskell/stack/releases/download/v1.5.0/stack-1.5.0-windows-x86_64.zip
- 7z x stack.zip stack.exe
build_script:
- stack.exe setup > nul
- stack.exe --no-terminal build --only-dependencies
test_script:
- stack.exe --no-terminal build --pedantic
- stack.exe sdist
after_test:
- ps: |
    cp "$(./stack.exe path --local-install-root)/bin/sensu-run.exe" sensu-run.exe
    7z a sensu-run.windows.zip sensu-run.exe
artifacts:
- path: sensu-run.windows.zip
deploy:
- provider: GitHub
  auth_token:
    secure: VfuGAeBDY+lUA7omIc8uMUNjvHwx34amMq34spLVP1nC0fR/ift6IGQCDguWipxF
  artifact: sensu-run.windows.zip
  release: $(appveyor_repo_tag_name)
  draft: true
  on:
    appveyor_repo_tag: true
